# version: "3.8"

services:
  geth:
    image: ethereum/client-go:v1.10.26
    ports:
      - "8545:8545"
      - "8546:8546"
    command:
      - --miner.gaslimit=12000000
      - --http
      - --http.api=personal,eth,net,web3,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws
      - --ws.api=personal,eth,net,web3,debug
      - --ws.addr=0.0.0.0
      - --ignore-legacy-receipts
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --dev
      - --verbosity=2
      - --nodiscover
      - --maxpeers=0
      - --mine
      - --miner.threads=1
      - --networkid=1337

  nginx:
    container_name: "nginx"
    image: nginx:1.24-alpine
    depends_on:
      - rundler-rpc
    ports:
      - "3030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rundler-pool:
    image: rundler
    container_name: "rundler-pool"
    depends_on:
      - geth
    command: pool
    environment:
      - RUST_LOG=debug
      - ENTRY_POINTS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
      - NODE_HTTP=http://geth:8545
      - MIN_UNSTAKE_DELAY=2
      - POOL_HOST=0.0.0.0
      - NETWORK=dev

  rundler-builder:
    image: rundler
    container_name: "rundler-builder"
    depends_on:
      - rundler-pool
    command: builder
    environment:
      - RUST_LOG=debug
      - ENTRY_POINTS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
      - NODE_HTTP=http://geth:8545
      - MIN_UNSTAKE_DELAY=2
      - BUILDER_PRIVATE_KEYS=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,575f4a2111f4f94160c7cc2b7472bb0b616d8c9d6b0fabdecf44c3c49322b8cd
      - BUILDER_POOL_URL=https://rundler-pool:50051
      - BUILDER_HOST=0.0.0.0
      - BUILDER_PORT=50051
      - NETWORK=dev

  rundler-rpc:
    image: rundler
    container_name: "rundler-rpc"
    depends_on:
      - rundler-builder
    command: rpc
    environment:
      - RUST_LOG=debug
      - ENTRY_POINTS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
      - NODE_HTTP=http://geth:8545
      - RPC_API=eth,debug
      - RPC_POOL_URL=https://rundler-pool:50051
      - RPC_BUILDER_URL=https://rundler-builder:50051
      - NETWORK=dev
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 10s
